### ISSUE TITLE
Usage of CC-BY-NC code.

### ISSUE THREAD

**Issue by brother** [CyrilCharlier/Bobissimo#2]
Hi
Not sure what your intended audience is but the project references highcharts and that module is dual licensed restricted source the free (gratis) code is under CC-BY-NC while you can buy a usage license if needed in a commercial project. 

Maybe consider changing that module to something else to make it easier to use the project in a commercial setting. Just a thought.

See also:
https://github.com/highcharts/highcharts/issues/4405#issuecomment-125124004
https://shop.highsoft.com/faq#Non-Commercial-0

**Comment by CyrilCharlier** [comment]
Google Translate  : 
_salut
Vous ne savez pas quel est votre public visé, mais le projet fait référence à des diagrammes élevés et ce module est une source restreinte sous licence autorisée. Le code gratuit (gratuit) est sous CC-BY-NC alors que vous pouvez acheter une licence d'utilisation si nécessaire dans un projet commercial.

Peut-être envisagez-vous de modifier ce module à autre chose pour faciliter l'utilisation du projet dans un contexte commercial. Juste une pensée._

**Comment by CyrilCharlier** [comment]
Google Translate : 
It is an open source project
